################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/Components/adv7533 \
Drivers/Components/exc7200 \
Drivers/Components/ft5336 \
Drivers/Components/ft6x06 \
Drivers/Components/mfxstm32l152 \
Drivers/Components/otm8009a \
Drivers/Components/ov9655 \
Drivers/Components/s5k5cag \
Drivers/Components/st7735 \
Drivers/Components/st7789h2 \
Drivers/Components/stmpe811 \
Drivers/Components/ts3510 \
Drivers/Components/wm8994 \
Drivers/Fonts \
Drivers/STM32F769I-Discovery \
Drivers/STM32F7xx_HAL_Driver/Src/Legacy \
Drivers/STM32F7xx_HAL_Driver/Src \
Drivers/hal_stm_lvgl/tft \
Drivers/hal_stm_lvgl/touchpad \
Drivers/lvgl/demos/benchmark/assets \
Drivers/lvgl/demos/benchmark \
Drivers/lvgl/demos/ebike/generated \
Drivers/lvgl/demos/ebike \
Drivers/lvgl/demos/ebike/translations \
Drivers/lvgl/demos/flex_layout \
Drivers/lvgl/demos/high_res/fonts \
Drivers/lvgl/demos/high_res \
Drivers/lvgl/demos/keypad_encoder \
Drivers/lvgl/demos \
Drivers/lvgl/demos/multilang/assets/avatars \
Drivers/lvgl/demos/multilang/assets/emojis \
Drivers/lvgl/demos/multilang/assets/fonts \
Drivers/lvgl/demos/multilang/assets \
Drivers/lvgl/demos/multilang \
Drivers/lvgl/demos/music/assets \
Drivers/lvgl/demos/music \
Drivers/lvgl/demos/render/assets \
Drivers/lvgl/demos/render \
Drivers/lvgl/demos/scroll \
Drivers/lvgl/demos/stress \
Drivers/lvgl/demos/transform/assets \
Drivers/lvgl/demos/transform \
Drivers/lvgl/demos/vector_graphic/assets \
Drivers/lvgl/demos/vector_graphic \
Drivers/lvgl/demos/widgets/assets \
Drivers/lvgl/demos/widgets \
Drivers/lvgl/env_support/pikascript \
Drivers/lvgl/env_support/rt-thread \
Drivers/lvgl/env_support/rt-thread/squareline \
Drivers/lvgl/examples/anim \
Drivers/lvgl/examples/assets \
Drivers/lvgl/examples/assets/emoji \
Drivers/lvgl/examples/event \
Drivers/lvgl/examples/get_started \
Drivers/lvgl/examples/layouts/flex \
Drivers/lvgl/examples/layouts/grid \
Drivers/lvgl/examples/libs/barcode \
Drivers/lvgl/examples/libs/bmp \
Drivers/lvgl/examples/libs/ffmpeg \
Drivers/lvgl/examples/libs/freetype \
Drivers/lvgl/examples/libs/gif \
Drivers/lvgl/examples/libs/libjpeg_turbo \
Drivers/lvgl/examples/libs/libpng \
Drivers/lvgl/examples/libs/lodepng \
Drivers/lvgl/examples/libs/qrcode \
Drivers/lvgl/examples/libs/rlottie \
Drivers/lvgl/examples/libs/svg \
Drivers/lvgl/examples/libs/tiny_ttf \
Drivers/lvgl/examples/libs/tjpgd \
Drivers/lvgl/examples/others/file_explorer \
Drivers/lvgl/examples/others/font_manager \
Drivers/lvgl/examples/others/fragment \
Drivers/lvgl/examples/others/gestures \
Drivers/lvgl/examples/others/gridnav \
Drivers/lvgl/examples/others/ime \
Drivers/lvgl/examples/others/imgfont \
Drivers/lvgl/examples/others/monkey \
Drivers/lvgl/examples/others/observer \
Drivers/lvgl/examples/others/snapshot \
Drivers/lvgl/examples/others/xml \
Drivers/lvgl/examples/porting \
Drivers/lvgl/examples/porting/osal \
Drivers/lvgl/examples/scroll \
Drivers/lvgl/examples/styles \
Drivers/lvgl/examples/widgets/animimg \
Drivers/lvgl/examples/widgets/arc \
Drivers/lvgl/examples/widgets/bar \
Drivers/lvgl/examples/widgets/button \
Drivers/lvgl/examples/widgets/buttonmatrix \
Drivers/lvgl/examples/widgets/calendar \
Drivers/lvgl/examples/widgets/canvas \
Drivers/lvgl/examples/widgets/chart \
Drivers/lvgl/examples/widgets/checkbox \
Drivers/lvgl/examples/widgets/dropdown \
Drivers/lvgl/examples/widgets/image \
Drivers/lvgl/examples/widgets/imagebutton \
Drivers/lvgl/examples/widgets/keyboard \
Drivers/lvgl/examples/widgets/label \
Drivers/lvgl/examples/widgets/led \
Drivers/lvgl/examples/widgets/line \
Drivers/lvgl/examples/widgets/list \
Drivers/lvgl/examples/widgets/lottie \
Drivers/lvgl/examples/widgets/menu \
Drivers/lvgl/examples/widgets/msgbox \
Drivers/lvgl/examples/widgets/obj \
Drivers/lvgl/examples/widgets/roller \
Drivers/lvgl/examples/widgets/scale \
Drivers/lvgl/examples/widgets/slider \
Drivers/lvgl/examples/widgets/span \
Drivers/lvgl/examples/widgets/spinbox \
Drivers/lvgl/examples/widgets/spinner \
Drivers/lvgl/examples/widgets/switch \
Drivers/lvgl/examples/widgets/table \
Drivers/lvgl/examples/widgets/tabview \
Drivers/lvgl/examples/widgets/textarea \
Drivers/lvgl/examples/widgets/tileview \
Drivers/lvgl/examples/widgets/win \
Drivers/lvgl/src/core \
Drivers/lvgl/src/display \
Drivers/lvgl/src/draw/dma2d \
Drivers/lvgl/src/draw \
Drivers/lvgl/src/draw/nema_gfx \
Drivers/lvgl/src/draw/nxp/pxp \
Drivers/lvgl/src/draw/nxp/vglite \
Drivers/lvgl/src/draw/opengles \
Drivers/lvgl/src/draw/renesas/dave2d \
Drivers/lvgl/src/draw/sdl \
Drivers/lvgl/src/draw/sw/blend/helium \
Drivers/lvgl/src/draw/sw/blend \
Drivers/lvgl/src/draw/sw/blend/neon \
Drivers/lvgl/src/draw/sw \
Drivers/lvgl/src/draw/vg_lite \
Drivers/lvgl/src/drivers/display/drm \
Drivers/lvgl/src/drivers/display/fb \
Drivers/lvgl/src/drivers/display/ili9341 \
Drivers/lvgl/src/drivers/display/lcd \
Drivers/lvgl/src/drivers/display/renesas_glcdc \
Drivers/lvgl/src/drivers/display/st7735 \
Drivers/lvgl/src/drivers/display/st7789 \
Drivers/lvgl/src/drivers/display/st7796 \
Drivers/lvgl/src/drivers/display/st_ltdc \
Drivers/lvgl/src/drivers/evdev \
Drivers/lvgl/src/drivers/glfw \
Drivers/lvgl/src/drivers/libinput \
Drivers/lvgl/src/drivers/nuttx \
Drivers/lvgl/src/drivers/qnx \
Drivers/lvgl/src/drivers/sdl \
Drivers/lvgl/src/drivers/uefi \
Drivers/lvgl/src/drivers/wayland \
Drivers/lvgl/src/drivers/windows \
Drivers/lvgl/src/drivers/x11 \
Drivers/lvgl/src/font \
Drivers/lvgl/src/indev \
Drivers/lvgl/src/layouts/flex \
Drivers/lvgl/src/layouts/grid \
Drivers/lvgl/src/layouts \
Drivers/lvgl/src/libs/barcode \
Drivers/lvgl/src/libs/bin_decoder \
Drivers/lvgl/src/libs/bmp \
Drivers/lvgl/src/libs/expat \
Drivers/lvgl/src/libs/ffmpeg \
Drivers/lvgl/src/libs/freetype \
Drivers/lvgl/src/libs/fsdrv \
Drivers/lvgl/src/libs/gif \
Drivers/lvgl/src/libs/libjpeg_turbo \
Drivers/lvgl/src/libs/libpng \
Drivers/lvgl/src/libs/lodepng \
Drivers/lvgl/src/libs/lz4 \
Drivers/lvgl/src/libs/qrcode \
Drivers/lvgl/src/libs/rle \
Drivers/lvgl/src/libs/rlottie \
Drivers/lvgl/src/libs/svg \
Drivers/lvgl/src/libs/tiny_ttf \
Drivers/lvgl/src/libs/tjpgd \
Drivers/lvgl/src \
Drivers/lvgl/src/misc/cache \
Drivers/lvgl/src/misc \
Drivers/lvgl/src/osal \
Drivers/lvgl/src/others/file_explorer \
Drivers/lvgl/src/others/font_manager \
Drivers/lvgl/src/others/fragment \
Drivers/lvgl/src/others/gridnav \
Drivers/lvgl/src/others/ime \
Drivers/lvgl/src/others/imgfont \
Drivers/lvgl/src/others/monkey \
Drivers/lvgl/src/others/observer \
Drivers/lvgl/src/others/snapshot \
Drivers/lvgl/src/others/sysmon \
Drivers/lvgl/src/others/vg_lite_tvg \
Drivers/lvgl/src/others/xml \
Drivers/lvgl/src/others/xml/parsers \
Drivers/lvgl/src/stdlib/builtin \
Drivers/lvgl/src/stdlib/clib \
Drivers/lvgl/src/stdlib \
Drivers/lvgl/src/stdlib/micropython \
Drivers/lvgl/src/stdlib/rtthread \
Drivers/lvgl/src/stdlib/uefi \
Drivers/lvgl/src/themes/default \
Drivers/lvgl/src/themes \
Drivers/lvgl/src/themes/mono \
Drivers/lvgl/src/themes/simple \
Drivers/lvgl/src/tick \
Drivers/lvgl/src/widgets/animimage \
Drivers/lvgl/src/widgets/arc \
Drivers/lvgl/src/widgets/bar \
Drivers/lvgl/src/widgets/button \
Drivers/lvgl/src/widgets/buttonmatrix \
Drivers/lvgl/src/widgets/calendar \
Drivers/lvgl/src/widgets/canvas \
Drivers/lvgl/src/widgets/chart \
Drivers/lvgl/src/widgets/checkbox \
Drivers/lvgl/src/widgets/dropdown \
Drivers/lvgl/src/widgets/image \
Drivers/lvgl/src/widgets/imagebutton \
Drivers/lvgl/src/widgets/keyboard \
Drivers/lvgl/src/widgets/label \
Drivers/lvgl/src/widgets/led \
Drivers/lvgl/src/widgets/line \
Drivers/lvgl/src/widgets/list \
Drivers/lvgl/src/widgets/lottie \
Drivers/lvgl/src/widgets/menu \
Drivers/lvgl/src/widgets/msgbox \
Drivers/lvgl/src/widgets/objx_templ \
Drivers/lvgl/src/widgets/property \
Drivers/lvgl/src/widgets/roller \
Drivers/lvgl/src/widgets/scale \
Drivers/lvgl/src/widgets/slider \
Drivers/lvgl/src/widgets/span \
Drivers/lvgl/src/widgets/spinbox \
Drivers/lvgl/src/widgets/spinner \
Drivers/lvgl/src/widgets/switch \
Drivers/lvgl/src/widgets/table \
Drivers/lvgl/src/widgets/tabview \
Drivers/lvgl/src/widgets/textarea \
Drivers/lvgl/src/widgets/tileview \
Drivers/lvgl/src/widgets/win \

